const documentActionTypes = {
  FETCH_DOCUMENTS_START: 'FETCH_DOCUMENTS_START',
  FETCH_DOCUMENTS_SUCCESS: 'FETCH_DOCUMENTS_SUCCESS',
  FETCH_DOCUMENTS_FAILURE: 'FETCH_DOCUMENTS_FAILURE',
  FETCH_OWNER_DOCUMENTS_START: 'FETCH_OWNER_DOCUMENTS_START',
  FETCH_OWNER_DOCUMENTS_FAILURE: 'FETCH_OWNER_DOCUMENTS_FAILURE',
  FETCH_OWNER_DOCUMENTS_SUCCESS: 'FETCH_OWNER_DOCUMENTS_SUCCESS',
  SELECT_DOCUMENT: 'SELECT_DOCUMENT',
};

export default documentActionTypes;
