const documentActionTypes = {
  FETCH_DOCUMENTS_START: 'FETCH_DOCUMENTS_START',
  FETCH_DOCUMENTS_SUCCESS: 'FETCH_DOCUMENTS_SUCCESS',
  FETCH_DOCUMENTS_FAILURE: 'FETCH_DOCUMENTS_FAILURE',
  FETCH_OWNER_DOCUMENTS_START: 'FETCH_OWNER_DOCUMENTS_START',
  FETCH_OWNER_DOCUMENTS_FAILURE: 'FETCH_OWNER_DOCUMENTS_FAILURE',
  FETCH_OWNER_DOCUMENTS_SUCCESS: 'FETCH_OWNER_DOCUMENTS_SUCCESS',
  SELECT_DOCUMENT: 'SELECT_DOCUMENT',
  CREATE_DOCUMENT_START: 'CREATE_DOCUMENT_START',
  CREATE_DOCUMENT_SUCCESS: 'CREATE_DOCUMENT_SUCCESS',
  CREATE_DOCUMENT_FAILURE: 'CREATE_DOCUMENT_FAILURE',
};

export default documentActionTypes;
