const userActionTypes = {
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  LOG_IN_START: 'LOG_IN_START',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  EDIT_USER_START: 'EDIT_USER_START',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAIL: 'EDIT_USER_FAIL',
};

export default userActionTypes;
